name: Docker Image CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Test the Docker image
        run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from web
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag nc-news-be:latest
