name: Docker Image CI

on: 
  pull_request:
    branches: 
      - master

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nc-news-be:latest
    - name: Test the Docker image
      run: WEB_IMAGE=nc-news-be:latest docker-compose --file docker-compose.test up
